### ISSUE TITLE
Introduction - Damian Osiak

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#25]
The ticket is about to introduce Damian Osiak into the project.
In the comment please describe what you can do and how you can help in this project and a bit about yourself
Also familiarize with what was done so far

**Comment by damianosiak** [comment]
I am familiar with HTML for creating simple and small-format websites using my own CSS styles, Bootstrap library and my own JavaScript scripts.
On the other hand, I am not familiar with JavaScript frameworks, so my projects are not very extensive.
I like to set myself specific tasks and complete them, because I am hardworking and determined to achieve my chosen goal.
I can also program in Java and use the JavaFX library.
On a daily basis, I professionally deal with the administration of Oracle Databases and basic administration of Linux (RedHat), PostgreSQL and Sybase SAP IQ.
