### ISSUE TITLE
Research deployment options

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#31]

**Comment by tomaszwylezek** [comment]
ticket has been finished - but we wait for confirmation about what has been achived as part of the ticket

**Comment by Physalium** [comment]
I learned about different hosting options and their pros and cons. After a deeper analysis, I chose Amazon S3 due to my knowledge of this provider and its enormous scaling possibilities. The first stage of deployment has been completed, leaving us with a basic website without a domain: https://d3onr91qduzv1q.cloudfront.net
