### ISSUE TITLE
Research business need

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#32]

**Comment by szymonbuniewicz** [comment]
| Questions                                                                                                                   | Answers                                                         |
| --------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------- |
| Is there anything lacking in the current apps?                                                                              | Offline functionality                                           |
| Is there anything lacking in the current apps?                                                                              | Priavcy concerns                                                |
| Would you be interested in participating in beta testing for an app that helps you find the best route?                     | Yes, I would love to                                            |
| Would you be interested in participating in beta testing for an app that helps you find the best route?                     | No                                                              |
| What features would you like to see in this kind of app?                                                                    | Real-time traffic updates                                       |
| What features would you like to see in this kind of app?                                                                    | Integration with calendar                                       |
| What features would you like to see in this kind of app?                                                                    | Possibility to print the route                                  |
| What are the main challenges you face when planning routes for multiple stops in your daily or professional life?           | Traffic delays affecting schedules                              |
| What are the main challenges you face when planning routes for multiple stops in your daily or professional life?           | Time-consuming manual planning                                  |
| What frustrations or limitations have you encountered with existing methods or tools?                                       | Limited customization options                                   |
| What frustrations or limitations have you encountered with existing methods or tools?                                       | Overly complicated UI                                           |
| Do you have any preferences for the types of devices on which you would like to use a route planning application?           | Prefer using a mobile app because of quick access from anywhere |
| Do you have any preferences for the types of devices on which you would like to use a route planning application?           | Desktop for more detailed planning                              |
| Are there any specific industries or scenarios in which you find route planning particularly challenging or time-consuming? | Trip planning                                                   |
| Are there any specific industries or scenarios in which you find route planning particularly challenging or time-consuming? | Delivery and logistics                                          |
| Are there any specific industries or scenarios in which you find route planning particularly challenging or time-consuming? | Event planning and scheduling                                   |
| What app do you usually use for trips?                                                                                      | Google Maps                                                     |
| What app do you usually use for trips?                                                                                      | Waze                                                            |
| What app do you usually use for trips?                                                                                      | Apple Maps                                                      |
