### ISSUE TITLE
Summary of business research

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#35]
Based on the result of #32 prepare a summary based on which we can plan some work to do.

**Comment by szymonbuniewicz** [comment]
There is a demand for a new route planning application that will offer features such as offline mode, live traffic updates and calendar integration. Also customization and an intuitive user interface are key factors in the success of a new application. There are different device preferences, so consider providing the app for different platforms. It's important to note that the ability to print a route is a significant aspect that many respondents mentioned as a crucial feature. This underscores the need to incorporate a route printing function in the new application to meet user expectations. There is also a need for beta testing to customize the app and address any functionality issues.

Therefore, to meet the expectations of users, our application should have:

- export route to pdf function, so users will be able to print the generated route,
- Web application, so that users will be able to use the application from different devices,
- See the generated route in, for example Google Maps, where they will be able to have live traffic updates,
- Intuitive UI and beta testing.
